openapi: 3.1.3
info:
  title: ichi-h/portfolio API
  version: 1.0.0
servers:
  - url: https://localhost:8800
    description: Local server
  - url: https://production.server.com
    description: Production server
tags:
  - name: Works
paths:
  /works/{slug}:
    $ref: ./paths/works/{slug}.yaml
  /works/filter:
    $ref: ./paths/works/filter.yaml
  /works/redeploy:
    $ref: ./paths/works/redeploy.yaml
components:
  securitySchemes:
    auth0:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://localhost/oauth/authorize
          tokenUrl: https://localhost/oauth/token
          scopes:
            create:works: create works
            read:works: read works
            update:works: update works
